"""Launch imperative navigation against a running physical Rosmaster M1."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    arguments = [
        DeclareLaunchArgument("goal_x", default_value="1.0", description="Goal X in /odom [m]."),
        DeclareLaunchArgument("goal_y", default_value="0.0", description="Goal Y in /odom [m]."),
        DeclareLaunchArgument("goal_tolerance", default_value="0.08",
                              description="Goal-arrival radius [m]."),
        DeclareLaunchArgument("enabled", default_value="false",
                              description="Enable physical motion only after the safety check."),
        DeclareLaunchArgument("max_speed", default_value="0.18", description="M1 speed cap [m/s]."),
        DeclareLaunchArgument("max_acceleration", default_value="0.25", description="M1 acceleration cap [m/s^2]."),
        DeclareLaunchArgument("robot_radius", default_value="0.18",
                              description="Physical robot radius used by the planner [m]."),
        DeclareLaunchArgument("safety_margin", default_value="0.18",
                              description="Additional planner clearance around the robot [m]."),
        DeclareLaunchArgument("front_safety_margin", default_value="0.18",
                              description="Additional planner clearance for obstacles in the forward cone [m]."),
        DeclareLaunchArgument("lateral_planning_margin", default_value="0.15",
                              description="Extra clearance for side corridor boundaries [m]."),
        DeclareLaunchArgument("front_planning_margin", default_value="0.15",
                              description="Extra clearance for forward obstacles [m]."),
        DeclareLaunchArgument("forward_obstacle_half_angle", default_value="45.0",
                              description="Half-angle of the forward obstacle cone [degrees]."),
        DeclareLaunchArgument("static_bypass_enabled", default_value="false",
                              description="Commit to one side while passing a centered static obstacle."),
        DeclareLaunchArgument("bypass_trigger_distance", default_value="0.75",
                              description="Start a static bypass for a blocker within this forward distance [m]."),
        DeclareLaunchArgument("bypass_lateral_gate", default_value="0.22",
                              description="Treat points within this goal-axis lateral distance as blockers [m]."),
        DeclareLaunchArgument("bypass_side_offset", default_value="0.24",
                              description="Temporary bypass-goal offset to the selected side [m]."),
        DeclareLaunchArgument("bypass_forward_offset", default_value="0.30",
                              description="Temporary bypass-goal offset beyond the blocker [m]."),
        DeclareLaunchArgument("bypass_release_distance", default_value="0.18",
                              description="Resume the final goal after passing this far beyond the blocker [m]."),
        DeclareLaunchArgument("bypass_speed", default_value="0.055",
                              description="Maximum holonomic speed for each static-bypass phase [m/s]."),
        DeclareLaunchArgument("bypass_goal_tolerance", default_value="0.06",
                              description="Distance for advancing a static-bypass phase [m]."),
        DeclareLaunchArgument("bypass_preferred_side", default_value="0",
                              description="Bypass side: 0 auto-selects wider LiDAR clearance; 1 left, -1 right."),
        DeclareLaunchArgument("trajectory_planner_enabled", default_value="true",
                              description="Use continuous receding-horizon holonomic trajectory planning."),
        DeclareLaunchArgument(
            "trajectory_horizon", default_value="20",
            description="20 rollout steps at 0.1 s give a two-second preview."),
        DeclareLaunchArgument("trajectory_heading_samples", default_value="41",
                              description="Number of sampled velocity headings per rollout."),
        DeclareLaunchArgument("trajectory_speed_samples", default_value="4",
                              description="Number of sampled speeds per rollout."),
        DeclareLaunchArgument("dynamic_obstacle_radius", default_value="0.20",
                              description="Radius assigned to each predicted moving-object track [m]."),
        DeclareLaunchArgument("moving_confirmation_age", default_value="3",
                              description="Consecutive moving observations required before dynamic prediction."),
        DeclareLaunchArgument("tf_max_age", default_value="0.30",
                              description="Maximum age of the latest odom<-laser TF [s]."),
        DeclareLaunchArgument("torch_num_threads", default_value="0",
                              description="PyTorch intra-op CPU threads; 0 keeps the platform default."),
        DeclareLaunchArgument("emergency_stop_distance", default_value="0.45",
                              description="Stop at or below this collision-tube distance [m]."),
        DeclareLaunchArgument("emergency_lateral_clearance", default_value="0.12",
                              description="Emergency collision-tube half-width around the translation direction [m]."),
    ]
    controller = Node(
        package="imperative_navigation",
        executable="imperative_m1_controller",
        name="imperative_m1_controller",
        output="screen",
        parameters=[{
            "goal_x": LaunchConfiguration("goal_x"),
            "goal_y": LaunchConfiguration("goal_y"),
            "goal_tolerance": LaunchConfiguration("goal_tolerance"),
            "enabled": LaunchConfiguration("enabled"),
            "max_speed": LaunchConfiguration("max_speed"),
            "max_acceleration": LaunchConfiguration("max_acceleration"),
            "robot_radius": LaunchConfiguration("robot_radius"),
            "safety_margin": LaunchConfiguration("safety_margin"),
            "front_safety_margin": LaunchConfiguration("front_safety_margin"),
            "lateral_planning_margin": LaunchConfiguration("lateral_planning_margin"),
            "front_planning_margin": LaunchConfiguration("front_planning_margin"),
            "forward_obstacle_half_angle": LaunchConfiguration("forward_obstacle_half_angle"),
            "static_bypass_enabled": LaunchConfiguration("static_bypass_enabled"),
            "bypass_trigger_distance": LaunchConfiguration("bypass_trigger_distance"),
            "bypass_lateral_gate": LaunchConfiguration("bypass_lateral_gate"),
            "bypass_side_offset": LaunchConfiguration("bypass_side_offset"),
            "bypass_forward_offset": LaunchConfiguration("bypass_forward_offset"),
            "bypass_release_distance": LaunchConfiguration("bypass_release_distance"),
            "bypass_speed": LaunchConfiguration("bypass_speed"),
            "bypass_goal_tolerance": LaunchConfiguration("bypass_goal_tolerance"),
            "bypass_preferred_side": LaunchConfiguration("bypass_preferred_side"),
            "trajectory_planner_enabled": LaunchConfiguration("trajectory_planner_enabled"),
            "trajectory_horizon": LaunchConfiguration("trajectory_horizon"),
            "trajectory_heading_samples": LaunchConfiguration("trajectory_heading_samples"),
            "trajectory_speed_samples": LaunchConfiguration("trajectory_speed_samples"),
            "dynamic_obstacle_radius": LaunchConfiguration("dynamic_obstacle_radius"),
            "moving_confirmation_age": LaunchConfiguration("moving_confirmation_age"),
            "tf_max_age": LaunchConfiguration("tf_max_age"),
            "torch_num_threads": LaunchConfiguration("torch_num_threads"),
            "emergency_stop_distance": LaunchConfiguration("emergency_stop_distance"),
            "emergency_lateral_clearance": LaunchConfiguration("emergency_lateral_clearance"),
            "scan_topic": "/scan",
            "odom_topic": "/odom",
            # The watchdog is deliberately launched separately. This planner
            # launch only publishes raw commands, so Ctrl+C cannot terminate
            # the independent process that continually owns /cmd_vel.
            "command_topic": "/imperative/cmd_vel_raw",
            "odom_frame": "odom",
        }],
    )
    return LaunchDescription(arguments + [controller])
